name: Upload & Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: upload-deploy-group
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - run: docker build -t chess -f Dockerfile .
      - run: docker save -o chess.tar chess

      - name: rsync container to server
        uses: burnett01/rsync-deployments@7.0.1 # takeout the shell script and use it directly?
        # and script needs hostname authentication as well.
        with:
          switches: -avzr --delete
          path: chess.tar
          remote_path: /home/a
          remote_host: ${{ secrets.SERVER_IP }}
          remote_user: a
          remote_key: ${{ secrets.SERVER_RSA_PRIV_KEY }}

      - name: docker load and run
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: a
          key: ${{ secrets.SERVER_RSA_PRIV_KEY }}
          script: dsi() { docker stop $(docker ps -a | awk -v i="^$1.*" '{if($2~i){print$1}}'); } && docker load -i /home/a/chess.tar && dsi chess || true && docker run -d -p 3000:9000 chess mono WebApp.exe